### ISSUE TITLE
No support for mkv files

### ISSUE THREAD

**Issue by chananshgong** [jiaaro/pydub#175] opened 2017-02-06 17:40 UTC
### Steps to reproduce
data= AudioSegment.from_file("file.mkv", "mkv")

### Expected behavior
should return the wav information into data

### Actual behavior
mkv is unknown format

**Comment by jiaaro** [comment] 2017-06-12 18:40
duplicate of #191 (closing this because that ticket has been more active)

**Closed by jiaaro** 2017-06-12 18:40 UTC
