### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by AliBaheri** [jiaaro/pydub#197] opened 2017-06-16 17:50 UTC
### Steps to reproduce
I wanted to install pydub on Mac form the source code. I am facing with the following error:

[Errno 13] Permission denied: '/Users/ali/anaconda/lib/python2.7/site-packages/easy-install.pth'

### Actual behavior

running install
install_dir /Users/ali/anaconda/lib/python2.7/site-packages/
running bdist_egg
running egg_info
writing pydub.egg-info/PKG-INFO
writing top-level names to pydub.egg-info/top_level.txt
writing dependency_links to pydub.egg-info/dependency_links.txt
reading manifest file 'pydub.egg-info/SOURCES.txt'
writing manifest file 'pydub.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/audio_segment.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/effects.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/exceptions.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/generators.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/logging_utils.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/playback.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/pyaudioop.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/scipy_effects.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/silence.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
copying build/lib/pydub/utils.py -> build/bdist.macosx-10.5-x86_64/egg/pydub
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/audio_segment.py to audio_segment.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/effects.py to effects.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/exceptions.py to exceptions.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/generators.py to generators.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/logging_utils.py to logging_utils.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/playback.py to playback.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/pyaudioop.py to pyaudioop.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/scipy_effects.py to scipy_effects.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/silence.py to silence.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pydub/utils.py to utils.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pydub.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pydub.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pydub.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pydub.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pydub-0.19.0-py2.7.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing pydub-0.19.0-py2.7.egg
removing '/Users/ali/anaconda/lib/python2.7/site-packages/pydub-0.19.0-py2.7.egg' (and everything under it)
creating /Users/ali/anaconda/lib/python2.7/site-packages/pydub-0.19.0-py2.7.egg
Extracting pydub-0.19.0-py2.7.egg to /Users/ali/anaconda/lib/python2.7/site-packages
Adding pydub 0.19.0 to easy-install.pth file
error: [Errno 13] Permission denied: '/Users/ali/anaconda/lib/python2.7/site-packages/easy-install.pth'

### Your System configuration
- Python version: 2.7
- Pydub version: 
- ffmpeg or avlib?: avilb

**Comment by AliBaheri** [comment] 2017-06-16 18:42
sudo chown -R $USER /usr/local does not work:(

**Comment by jiaaro** [comment] 2017-06-16 18:44
the file it's not allowed to touch is in `/Users/ali/anaconda` so if you were going to chown it'd be:

```
$ chown -R $USER /Users/ali/anaconda
```

I'm not sure what other side effects though could have though (I don't use anaconda on a day to day basis)

**Comment by AliBaheri** [comment] 2017-06-17 12:21
Thanks for your suggestion. But I am not able to install package yet.

**Comment by jiaaro** [comment] 2019-06-01 02:53
Closing this issue due to it's age, and because, unfortunately, the problem is outside the scope of the project (I think)

**Closed by jiaaro** 2019-06-01 02:53 UTC
